baseURL: https://www.luratic.com
DefaultContentLanguage: es
title: "LURATIC"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 6
    ordered: false
colors:
  background: "#fff"
# Enable Google Analytics
googleAnalytics: 

# Enable Disqus forum
disqusShortname: 

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  languageCode: es-es
  language: es
  # Enable Google Tag Manager
  gtm_id : "GTM-5D7RV9H"
  gtm_datalayer : "basic"
  # Copyright Notice
  copyright: © 2020 Copyright.

  # Meta description for your site.  This will help the search engines to find your site.
  description: This is a Luratic Web.

  # background image of the landing page
  background: "images/background.png"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will be default to the theme logos if not provided.
  logo:
    main: /images/logo-white.png
    inverted: /images/logo-white.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/luratic/bathackers

  # specify whether you want to write blog post or not
  enableBlogPost: false

  # specify whether you want to show Table of Contents in reading page
  enableTOC: false

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  # customMenus:
  # - name: Templates
  #   url: "https://tagmanager.google.com/gallery/#/?filter=precariostecnicos&page=1"

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false

  # some information about you
  author:
    name: "Luratic"
    nickname: "Luratic"
    image: "images/avatar.png"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "info@luratic.com"
      #phone: "+0123456789"
    # a summary of what you do
    summary:
    - We are  Digital Analytics.
    - We are Implementation Specialist.
    - "One tag: good, better, best."
